// ------------------------------------------------
// ASYNC ACTION: GET LEAVE REQUEST FOR APPROVAL
export const GET_LIST_LEAVE_REQUEST = 'GET_LIST_LEAVE_REQUEST';
export const GET_LIST_LEAVE_REQUEST_PENDING = 'GET_LIST_LEAVE_REQUEST_PENDING';
export const GET_LIST_LEAVE_REQUEST_SUCCESS = 'GET_LIST_LEAVE_REQUEST_SUCCESS';
export const GET_LIST_LEAVE_REQUEST_ERROR = 'GET_LIST_LEAVE_REQUEST_ERROR';
export const UPDATE_ROW_INDEX_LIST_LEAVE_REQUEST = 'UPDATE_ROW_INDEX_LIST_LEAVE_REQUEST';
export const UPDATE_FLATLIST_READY_LIST_LEAVE_REQUEST = 'UPDATE_FLATLIST_READY_LIST_LEAVE_REQUEST';
// ------------------------------------------------
// ASYNC ACTION: LOAD MORE_LIST_LEAVE_REQUEST
export const LOAD_MORE_LIST_LEAVE_REQUEST = 'LOAD_MORE_LIST_LEAVE_REQUEST';
export const LOAD_MORE_LIST_LEAVE_REQUEST_PENDING = 'LOAD_MORE_LIST_LEAVE_REQUEST_PENDING';
export const LOAD_MORE_LIST_LEAVE_REQUEST_SUCCESS = 'LOAD_MORE_LIST_LEAVE_REQUEST_SUCCESS';
export const LOAD_MORE_LIST_LEAVE_REQUEST_ERROR = 'LOAD_MORE_LIST_LEAVE_REQUEST_ERROR';
// ------------------------------------------------
// ASYNC ACTION: GET LEAVE TYPE
export const GET_LEAVE_REQUEST_TYPE = 'GET_LEAVE_REQUEST_TYPE';
export const GET_LEAVE_REQUEST_TYPE_PENDING = 'GET_LEAVE_REQUEST_TYPE_PENDING';
export const GET_LEAVE_REQUEST_TYPE_SUCCESS = 'GET_LEAVE_REQUEST_TYPE_SUCCESS';
export const GET_LEAVE_REQUEST_TYPE_ERROR = 'GET_LEAVE_REQUEST_TYPE_ERROR';
// ------------------------------------------------
// ASYNC ACTION: CREATE NEW LEAVE REQUEST
export const CREATE_NEW_LEAVE_REQUEST = 'CREATE_NEW_LEAVE_REQUEST'
export const CREATE_NEW_LEAVE_REQUEST_PENDING = 'CREATE_NEW_LEAVE_REQUEST_PENDING';
export const CREATE_NEW_LEAVE_REQUEST_SUCCESS = 'CREATE_NEW_LEAVE_REQUEST_SUCCESS';
export const CREATE_NEW_LEAVE_REQUEST_ERROR = 'CREATE_NEW_LEAVE_REQUEST_ERROR';
// ------------------------------------------------
// ASYNC ACTION: GET LEAVE REQUEST FOR APPROVAL
export const GET_LEAVE_REQUEST_FOR_APPROVAL = 'GET_LEAVE_REQUEST_FOR_APPROVAL';
export const GET_LEAVE_REQUEST_FOR_APPROVAL_PENDING = 'GET_LEAVE_REQUEST_FOR_APPROVAL_PENDING';
export const GET_LEAVE_REQUEST_FOR_APPROVAL_SUCCESS = 'GET_LEAVE_REQUEST_FOR_APPROVAL_SUCCESS';
export const GET_LEAVE_REQUEST_FOR_APPROVAL_ERROR = 'GET_LEAVE_REQUEST_FOR_APPROVAL_ERROR';
// ------------------------------------------------
// ASYNC ACTION: LOAD MORE_LIST_LEAVE_REQUEST
export const LOAD_MORE_LEAVE_REQUEST_FOR_APPROVAL = 'LOAD_MORE_LEAVE_REQUEST_FOR_APPROVAL';
export const LOAD_MORE_LEAVE_REQUEST_FOR_APPROVAL_PENDING = 'LOAD_MORE_LEAVE_REQUEST_FOR_APPROVAL_PENDING';
export const LOAD_MORE_LEAVE_REQUEST_FOR_APPROVAL_SUCCESS = 'LOAD_MORE_LEAVE_REQUEST_FOR_APPROVAL_SUCCESS';
export const LOAD_MORE_LEAVE_REQUEST_FOR_APPROVAL_ERROR = 'LOAD_MORE_LEAVE_REQUEST_FOR_APPROVAL_ERROR';
// ------------------------------------------------
// ASYNC ACTION: APPROVE LEAVE REQUEST
export const APPROVE_LEAVE_REQUEST = 'APPROVE_LEAVE_REQUEST';
export const APPROVE_LEAVE_REQUEST_PENDING = 'APPROVE_LEAVE_REQUEST_PENDING';
export const APPROVE_LEAVE_REQUEST_SUCCESS = 'APPROVE_LEAVE_REQUEST_SUCCESS';
export const APPROVE_LEAVE_REQUEST_ERROR = 'APPROVE_LEAVE_REQUEST_ERROR';
// ------------------------------------------------
// ASYNC ACTION: REJECT LEAVE REQUEST
export const REJECT_LEAVE_REQUEST = 'REJECT_LEAVE_REQUEST';
export const REJECT_LEAVE_REQUEST_PENDING = 'REJECT_LEAVE_REQUEST_PENDING';
export const REJECT_LEAVE_REQUEST_SUCCESS = 'REJECT_LEAVE_REQUEST_SUCCESS';
export const REJECT_LEAVE_REQUEST_ERROR = 'REJECT_LEAVE_REQUEST_ERROR';



