// ------------------------------------------------
// ASYNC ACTION: EMPLOYEES
export const EMPLOYEES_DETAIL = 'EMPLOYEES_DETAIL'
export const EMPLOYEES_DETAIL_PENDING = 'EMPLOYEES_DETAIL_PENDING';
export const EMPLOYEES_DETAIL_SUCCESS = 'EMPLOYEES_DETAIL_SUCCESS';
export const EMPLOYEES_DETAIL_ERROR = 'EMPLOYEES_DETAIL_ERROR';